from django.urls import path
from . import views

urlpatterns = [
    path('admin', views.principal, name='principal'),
    path('usuario/listaUser/<int:pk>/', views.detalle_usuario, name='detalle_usuario'),
    path('admin/listaChofer/', views.listado_chofer, name='listado_chofer'),
    path('admin/listaPersona/', views.listado_persona, name= 'listado_persona'),
    path('admin/listaUser/', views.lisatdo_usuario, name='listado_usuario'),
    path('admin/listaPasajero', views.lisatdo_pasajero, name='listado_pasajero'),
    path('admin/listaCombi', views.listado_combi, name='listado_combi'),
    path('admin/listaViaje', views.listado_viaje ,name='listado_viaje'),
    path('admin/listaInsumo',views.listado_insumo ,name='listado_insumo'),
    path('admin/listaRuta',views.listado_ruta ,name='listado_ruta'),
    path('admin/listaLugar', views.listado_lugar ,name='listado_lugar'),
    path('admin/listaTarjeta', views.listado_tarjeta ,name='listado_tarjeta'),
    path('admin/lugarNew', views.lugar_new, name='lugar_new'),
    path('admin/choferNew', views.chofer_new, name='chofer_new'),
    path('admin/combiNew', views.combi_new, name='combi_new'),
    path('admin/viajeNew', views.viaje_new, name='viaje_new'),
    path('admin/insumoNew', views.insumo_new, name='insumo_new'),
    path('admin/rutaNew', views.ruta_new, name= 'ruta_new'),
    path('registrar/',views.pasajero_new , name='registrar'),
    path('admin/listaPasajero/<int:pk>/', views.detalle_pasajero, name='detalle_pasajero'),
    path('admin/listaChofer/<int:pk>/', views.detalle_chofer, name='detalle_chofer'),
    path('admin/listaCombi/<int:pk>/', views.detalle_combi, name='detalle_combi'),
    path('admin/listaViaje/<int:pk>/', views.detalle_viaje, name='detalle_viaje'),
    path('admin/listaRuta/<int:pk>/', views.detalle_ruta, name='detalle_ruta'),
    path('admin/listaTarjeta/<int:pk>/', views.detalle_tarjeta, name='detalle_tarjeta'),
    path('admin/listaInsumo/<int:pk>/', views.detalle_insumo, name='detalle_insumo'),
    path('admin/listaLugar/<int:pk>/', views.detalle_lugar, name='detalle_lugar'),
    path('admin/listaLugar/modificar/<int:pk>/', views.modificar_lugar, name='modificar_lugar'),
    path('admin/listaInsumo/modificar/<int:pk>/', views.modificar_insumo, name='modificar_insumo'),
    path('admin/listaRuta/modificar/<int:pk>/', views.modificar_ruta, name='modificar_ruta'),
    path('admin/listaChofer/modificar/<int:pk>/', views.modificar_chofer, name='modificar_chofer'),
    path('admin/listaCombi/modificar/<int:pk>/', views.modificar_combi, name='modificar_combi'),
    path('admin/listaViaje/modificar/<int:pk>/', views.modificar_viaje, name='modificar_viaje'),
    path('admin/listaLugar/eliminar/<int:pk>/', views.eliminar_lugar, name='eliminar_lugar'),
    path('admin/listaChofer/eliminar/<int:pk>/', views.eliminar_chofer, name='eliminar_chofer'),
    path('admin/listaCombi/eliminar/<int:pk>/', views.eliminar_combi, name='eliminar_combi'),
    path('admin/listaViaje/eliminar/<int:pk>/', views.eliminar_viaje, name='eliminar_viaje'),
    path('admin/listaInsumo/eliminar/<int:pk>/', views.eliminar_insumo, name='eliminar_insumo'),
    path('admin/listaRuta/eliminar/<int:pk>/', views.eliminar_ruta, name='eliminar_ruta'),
    path('login/',views.login_usuario,name='login'),
    path('registrar_tarjeta/',views.tarjeta_new,name="registrar_tarjeta"),
    path('home_usuario/',views.home_usuario,name="home_usuario"),
    path('logout/',views.logout_usuario,name='logout')
]
