# Generated by Django 3.2 on 2021-05-21 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='viaje',
            name='vendidos',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='persona',
            name='dni',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='tarjeta',
            name='numero',
            field=models.BigIntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='viaje',
            unique_together=set(),
        ),
    ]
