# Generated by Django 3.2 on 2021-05-08 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo1', '0002_rename_fecha_de_nacimiento_pasajero_fecha_de_nacimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='lugar',
            name='activo',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
