# Generated by Django 3.2 on 2021-05-21 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo1', '0002_auto_20210520_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viaje',
            name='insumos',
            field=models.ManyToManyField(blank=True, to='demo1.Insumo'),
        ),
    ]
