# Generated by Django 3.2 on 2021-05-23 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo1', '0003_alter_viaje_insumos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pasajero',
            name='tipo',
            field=models.CharField(choices=[('BASIC', 'BASIC'), ('GOLD', 'GOLD')], max_length=5),
        ),
    ]
