# Generated by Django 3.2 on 2021-05-08 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo1', '0003_lugar_activo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lugar',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
