# Generated by Django 2.2.20 on 2021-05-23 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo1', '0006_auto_20210523_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
