# Generated by Django 3.2 on 2021-05-24 03:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demo1', '0007_comentario_activo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='combi',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='lugar',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='ruta',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tarjeta',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='viaje',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='Pasaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'PENDIENTE'), ('CANCELADO', 'CANCELADO'), ('ENCURSO', 'ENCURSO'), ('RECHAZADO', 'RECHAZADO'), ('PASADO', 'PASADO')], max_length=9)),
                ('activo', models.BooleanField(default=True)),
                ('cantidad', models.IntegerField()),
                ('costoTotal', models.FloatField()),
                ('costoDevuelto', models.FloatField()),
                ('insumos', models.ManyToManyField(blank=True, to='demo1.Insumo')),
                ('pasajero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo1.pasajero')),
                ('viaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo1.viaje')),
            ],
        ),
    ]
