# Generated by Django 2.2.20 on 2021-06-06 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo1', '0011_auto_20210606_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='fecha',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='hora',
            field=models.TimeField(),
        ),
    ]
