# Generated by Django 2.2.20 on 2021-06-11 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo1', '0012_auto_20210606_1744'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentario',
            name='viaje',
        ),
    ]
