# Generated by Django 3.2 on 2021-06-25 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo1', '0014_auto_20210624_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='pasajero',
            name='fecha_habilitacion',
            field=models.DateField(auto_now=True),
        ),
    ]
