# Generated by Django 3.2 on 2021-06-26 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo1', '0016_auto_20210625_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pasaje',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'PENDIENTE'), ('ACEPTADO', 'ACEPTADO'), ('CANCELADO', 'CANCELADO'), ('ENCURSO', 'ENCURSO'), ('RECHAZADO', 'RECHAZADO'), ('PASADO', 'PASADO')], max_length=9),
        ),
    ]
